# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='media/')),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
